### ISSUE TITLE
🐞 - Cannot create proxy with a non-object as target or handler

### ISSUE THREAD

**Issue by vladimirpotekhin** [taiga-family/ng-polymorpheus#232]
### Playground Link

https://stackblitz.com/edit/angular-gwybp9?file=src%2Fapp%2Fapp.component.html

### Description

error occurs when using primitive as context in tooltip

<img width="527" alt="Снимок экрана 2023-12-27 в 13 57 04" src="https://github.com/taiga-family/ng-polymorpheus/assets/46284632/dd8d5cdb-fb36-4771-8909-54af98cebe4e">

related #175

### Angular version

12>

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Not sure this is a valid error. Maybe we should just document context better, that it has to be an object? Supporting a primitive makes it impossible to use with templates, which breaks uniformity. However sometimes primitive does make sense, if we intent on using functions or components only 🤔
